### ISSUE TITLE
error on the install kaldilm

### ISSUE THREAD

**Issue by shanguanma** [k2-fsa/snowfall#237]
I am install snowfall via `cd snowfall; python3 -m pip install -e .`, however I got the error is as follows:
```
 Building wheel for kaldilm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/maduo/anaconda3/envs/k2-fsa/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2s5z255s/kaldilm_ac45d1df260c4990bcb5822bda017023/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2s5z255s/kaldilm_ac45d1df260c4990bcb5822bda017023/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-146km3jy
       cwd: /tmp/pip-install-2s5z255s/kaldilm_ac45d1df260c4990bcb5822bda017023/
  Complete output (53 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/kaldilm
  copying kaldilm/python/kaldilm/__init__.py -> build/lib.linux-x86_64-3.8/kaldilm
  copying kaldilm/python/kaldilm/arpa2fst.py -> build/lib.linux-x86_64-3.8/kaldilm
  copying kaldilm/python/kaldilm/__main__.py -> build/lib.linux-x86_64-3.8/kaldilm
  running build_ext
  sh: 1: cmake: not found
  make: *** No rule to make target '_kaldilm'.  Stop.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-2s5z255s/kaldilm_ac45d1df260c4990bcb5822bda017023/setup.py", line 60, in <module>
      setuptools.setup(
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/site-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 87, in run
      _build_ext.run(self)
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/home/maduo/anaconda3/envs/k2-fsa/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-2s5z255s/kaldilm_ac45d1df260c4990bcb5822bda017023/setup.py", line 32, in build_extension
      raise Exception(
  Exception:
  Build kaldilm failed. Please check the error message.
  You can ask for help by creating an issue on GitHub.
  
  Click:
      https://github.com/csukuangfj/kaldilm/issues/new
  
  ----------------------------------------
  ERROR: Failed building wheel for kaldilm
  Running setup.py clean for kaldilm
Failed to build kaldilm
```

**Comment by csukuangfj** [comment]
>   sh: 1: cmake: not found


Please install CMake first.

One approach to install CMake is given below (you may use other methods if you like)

```bash
# Assume you want to install CMake to $HOME/software/cmake-3.18

cd $HOME
wget https://github.com/Kitware/CMake/releases/download/v3.18.6/cmake-3.18.6-Linux-x86_64.sh
chmod +x cmake-3.18.6-Linux-x86_64.sh
./cmake-3.18.6-Linux-x86_64.sh --prefix=$HOME/software/cmake-3.18 --skip-license
export PATH=$HOME/software/cmake-3.18/bin:$PATH
cmake --version. # it should display the version of CMake you just installed
```

**Comment by csukuangfj** [comment]
I find that you are using conda
```
/home/maduo/anaconda3/envs
```

Please just run:
```
conda install -c k2-fsa kaldilm
```

**Comment by shanguanma** [comment]
@csukuangfj ,thanks a lot, solved it, closed
