### ISSUE TITLE
AttributeError: Unknown attribute 

### ISSUE THREAD

**Issue by lianrzh** [k2-fsa/snowfall#30]
I met the error when run stage 6 ` python train.py`
`
$ python train.py
/data/app/anaconda3/envs/k2/lib/python3.7/site-packages/lhotse/augmentation/torchaudio.py:13: UserWarning: Torchaudio SoX effects chains are only introduced in version 0.7 - please upgrade your PyTorch to 1.7+ and torchaudio to 0.7+ to use them.
  warnings.warn('Torchaudio SoX effects chains are only introduced in version 0.7 - '
Loading L.fst
About to get train cuts
About to get dev cuts
About to create train dataset
About to create dev dataset
About to create train dataloader
About to create dev dataloader
About to create model
2020-11-26 16:30:17,713 INFO [train.py:297] epoch 0, learning rate 1e-05
Traceback (most recent call last):
  File "train.py", line 347, in <module>
    main()
  File "train.py", line 307, in main
    num_epochs=num_epochs)
  File "train.py", line 153, in train_one_epoch
    get_objf(batch, model, subsampling, device, L, symbols, True, optimizer)
  File "train.py", line 103, in get_objf
    decoding_graph = create_decoding_graph(texts, L, symbols).to(device)
  File "/data/app/anaconda3/envs/k2/lib/python3.7/site-packages/k2/fsa.py", line 240, in __getattr__
    raise AttributeError(f'Unknown attribute {name}')
AttributeError: Unknown attribute to

`

**Comment by danpovey** [comment]
Probably you have an older version of k2, before .to() was added to Fsa.

**Comment by csukuangfj** [comment]
Initially, there was only `to_`, no `to`. Pay attention to the trailing underscore.
