### ISSUE TITLE
LSTM model

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/snowfall#43]
Right now decode.py is giving very terrible WER, over 90%, even after tuning bias_penalty.
Would be  nice  if someone can try using an LSTM model (needed to give spiky outputs so CTC can work.)

Dunno if this is the issue or it's some other bug.

**Comment by danpovey** [comment]
.. right now I'm busy on a decoder (intersect_pruned) rewrite to use less memory.

**Comment by danpovey** [comment]
Community help welcomed.

**Comment by pzelasko** [comment]
I'll look into it. I'm also looking at other aspects of the recipe - e.g. we're currently using position dependent phones, so we're getting 4x the number of output symbols and I think it could be hurtful.

**Comment by danpovey** [comment]
Great!

**Comment by pzelasko** [comment]
Hmm I'm getting this issue in `decode.py`, I'm using latest k2, could this be some regression?

```
Traceback (most recent call last):
  File "decode.py", line 176, in <module>
    main()
  File "decode.py", line 111, in main
    aux_labels_disambig_id_start=200004)
  File "/home/pzelasko/snowfall/snowfall/decoding/graph.py", line 36, in compile_LG
    LG.aux_labels[LG.aux_labels >= aux_labels_disambig_id_start] = 0
TypeError: '>=' not supported between instances of '_k2.RaggedInt' and 'int'
```

Anyway I changed the phones to position independent and that's how an example of posteriors looks like in an unmodified model (the first is the "as-is" output, the other one is `exp(posteriors)` to check if there are spikes or not):

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/15930688/102444815-10217700-3ff8-11eb-991f-89a7b85c89d3.png">

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/15930688/102444830-17488500-3ff8-11eb-926a-4f169bb1c186.png">

To me the acoustic model looks okay-ish (although I should probably further shrink the output layers by removing the disambiguation symbols, which are the last few rows in the posterior matrix).

**Comment by pzelasko** [comment]
(this is in the middle of training, i.e. checkpoint from epoch 5)

**Comment by pzelasko** [comment]
Update: never mind, it was not the latest k2, and the WER for that model is still 99%. Almost all the hypotheses are empty texts. Will keep looking.

**Comment by Curisan** [comment]
It seems there is a small bug in train.py and decode.py.  In train.py：
```
 supervision_segments = supervision_segments[indices]

    texts = supervisions['text']
    assert feature.ndim == 3
    # print(supervision_segments[:, 1] + supervision_segments[:, 2])
```
The "texts" is not reorder by indices, while supervision_segments have been reorder. And in decode.py there is same bug.
I reorder "texts" by indices and retrain the model, the WER reduce to 87.01% after 5 epoches.

**Comment by pzelasko** [comment]
FYI I ran the full 960h librispeech training (with speed perturbation) with the CTC graph, the WER is:

```
2021-01-03 08:53:22,337 INFO [decode.py:217] %WER 10.05% [5285 / 52576, 725 ins, 436 del, 4124 sub ]
```

I think the difference is really small between this and the `train-clean-100` result (12~13%), could be due to a small (or "weak") model architecture.

**Comment by danpovey** [comment]
Thanks!
That difference is what I would expect.  We'd need a larger model to get
more benefit, I think.
