### ISSUE TITLE
about error of asg_train.py 

### ISSUE THREAD

**Issue by shanguanma** [k2-fsa/snowfall#66]
I follow `librispeech/asr/simple_v1/` recipe example, and rebuild k2 newest master(2021-1-4).
When I run `python3 asg_train.py` , It gives the following error:
```
scores: tensor([ 1.9269,  1.4873,  0.9007,  ...,  0.0990, -1.0238, -1.6546])
scores shape is :  torch.Size([52899])
Traceback (most recent call last):
  File "asg_train.py", line 430, in <module>
    main()
  File "asg_train.py", line 297, in main
    P.set_scores_stochastic_(scores)
TypeError: set_scores_stochastic_() takes 1 positional argument but 2 were given
```
I think it is a bug.

**Comment by csukuangfj** [comment]
Please refer to
https://github.com/k2-fsa/snowfall/pull/62#issuecomment-753284760

**Comment by csukuangfj** [comment]
Please use https://github.com/k2-fsa/k2/pull/563
It has not been merged yet.

**Comment by shanguanma** [comment]
OK, thanks, I will try it.

**Comment by csukuangfj** [comment]
Could you please post your result here when the decoding is done? 
Just want to make sure that ASG training can be reproduced.

**Comment by shanguanma** [comment]
> Could you please post your result here when the decoding is done?
> Just want to make sure that ASG training can be reproduced.

Yes, of course. Once completed, I will summarize the results here.
