### ISSUE TITLE
TypeError when remove values from LG.aux_labels

### ISSUE THREAD

**Issue by Jarvan-Wang** [k2-fsa/snowfall#67]
When run decode.py of librispeech egs, got:
`Traceback (most recent call last):
  File "./decode.py", line 224, in <module>
    main()
  File "./decode.py", line 192, in main
    LG.aux_labels = k2.ragged.remove_values_eq(LG.aux_labels, 0)
  File "/search/speech/wangjiawen/anaconda2/envs/k2/lib/python3.7/site-packages/k2/ragged/ops.py", line 75, in remove_values_eq
    return _k2.ragged_int_remove_values_eq(src, target)
TypeError: ragged_int_remove_values_eq(): incompatible function arguments. The following argument types are supported:
    1. (src: _k2.RaggedInt, target: int) -> _k2.RaggedInt

Invoked with: tensor([  0,   0,  50,  ..., 340,   1,   1], device='cuda:0',
       dtype=torch.int32), 0
`
implicit conversion from torch.tensor to k2.RaggedInt not supported?

**Comment by csukuangfj** [comment]
Does the problem disappear for the latest k2, i.e., k2 master branch?

**Comment by Jarvan-Wang** [comment]
> Does the problem disappear for the latest k2, i.e., k2 master branch?

yes
k2 commit is https://github.com/k2-fsa/k2/commit/4c629e1d476e026efce4c8e90d1c12ec872b9b60
snowfall commit is 17fee77c8f5fd0acdb37bffec95aa7e489a18650

**Comment by csukuangfj** [comment]
1. Did you change anything locally?
2. Did you reuse `data/lang_nosp/LG.pt` ?

Could you post the log of running `decode.py` ?

**Comment by Jarvan-Wang** [comment]
> 1. Did you change anything locally?
> 2. Did you reuse `data/lang_nosp/LG.pt` ?
> 
> Could you post the log of running `decode.py` ?

1. No
2. Yes, but I tried re-intersect LG.pt, problem is the same
log is below:


$ CUDA_VISIBLE_DEVICES=4 ./decode.py
/search/speech/wangjiawen/anaconda2/envs/k2/lib/python3.7/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
Loading L_disambig.fst.txt
Loading G.fsa.txt
2021-01-05 14:31:22,394 DEBUG [graph.py:32] Intersecting L and G
2021-01-05 14:32:27,928 DEBUG [graph.py:34] LG shape = (22039515, None)
2021-01-05 14:32:27,929 DEBUG [graph.py:35] Connecting L*G
2021-01-05 14:32:44,475 DEBUG [graph.py:37] LG shape = (0, None)
2021-01-05 14:32:44,476 DEBUG [graph.py:38] Determinizing L*G
2021-01-05 14:32:44,476 DEBUG [graph.py:40] LG shape = (0, None)
2021-01-05 14:32:44,476 DEBUG [graph.py:41] Connecting det(L*G)
2021-01-05 14:32:44,476 DEBUG [graph.py:43] LG shape = (0, None)
2021-01-05 14:32:44,476 DEBUG [graph.py:44] Removing disambiguation symbols on L*G
2021-01-05 14:32:44,549 DEBUG [graph.py:50] Removing epsilons
2021-01-05 14:32:44,550 DEBUG [graph.py:52] LG shape = (0, None)
2021-01-05 14:32:44,550 DEBUG [graph.py:53] Connecting rm-eps(det(L*G))
2021-01-05 14:32:44,550 DEBUG [graph.py:55] LG shape = (0, None)
Traceback (most recent call last):
  File "./decode.py", line 224, in <module>
    main()
  File "./decode.py", line 156, in main
    aux_labels_disambig_id_start=first_word_disambig_id)
  File "/search/speech/wangjiawen/anaconda2/envs/k2/lib/python3.7/site-packages/snowfall-0.1-py3.7.egg/snowfall/decoding/graph.py", line 56, in compile_LG
  File "/search/speech/wangjiawen/anaconda2/envs/k2/lib/python3.7/site-packages/k2/ragged/ops.py", line 80, in remove_values_eq
    return _k2.ragged_int_remove_values_eq(src, target)
TypeError: ragged_int_remove_values_eq(): incompatible function arguments. The following argument types are supported:
    1. (src: _k2.RaggedInt, target: int) -> _k2.RaggedInt

Invoked with: tensor([], dtype=torch.int32), 0

**Comment by csukuangfj** [comment]
> Loading G.fsa.txt
2021-01-05 14:31:22,394 DEBUG [graph.py:32] Intersecting L and G
2021-01-05 14:32:27,928 DEBUG [graph.py:34] LG shape = (22039515, None)
2021-01-05 14:32:27,929 DEBUG [graph.py:35] Connecting LG
2021-01-05 14:32:44,475 DEBUG [graph.py:37] LG shape = (0, None)

Does your `G.fsa.txt`  use the same word table with your `L`?  You can see that after `L o G`, the resulting FSA is empty,
this is not reasonable.

**Comment by Jarvan-Wang** [comment]
> > Loading G.fsa.txt
> > 2021-01-05 14:31:22,394 DEBUG [graph.py:32] Intersecting L and G
> > 2021-01-05 14:32:27,928 DEBUG [graph.py:34] LG shape = (22039515, None)
> > 2021-01-05 14:32:27,929 DEBUG [graph.py:35] Connecting LG
> > 2021-01-05 14:32:44,475 DEBUG [graph.py:37] LG shape = (0, None)
> 
> Does your `G.fsa.txt` use the same word table with your `L`? You can see that after `L o G`, the resulting FSA is empty,
> this is not reasonable.

After reproduce L and G, its works. But why?
why _k2.ragged_int_remove_values_eq(src, target) cannot Invoked with
tensor([ 0, 0, 50, ..., 340, 1, 1], device='cuda:0', dtype=torch.int32), 0)
