### ISSUE TITLE
Fix ctc_train.py

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/snowfall#87]
Validation objf printed wrongly:
```
2021-02-04 00:46:32,788 INFO [ctc_train.py:181] batch 1200, epoch 0/8 global average objf: 0.424166 over 35729217.0 frames (100.0% kept), current batch average objf: 0.310550 over 29935 frames (100.0% kept) avg time waiting for batch 0.006s
2021-02-04 00:47:04,007 INFO [ctc_train.py:212] Validation average objf: 46.677417 over 645831.0 frames (100.0% kept)
```
error:
```
Traceback (most recent call last):
  File "ctc_train.py", line 399, in <module>
    main()
  File "ctc_train.py", line 362, in main
    save_checkpoint(filename=best_model_path,
TypeError: save_checkpoint() missing 2 required positional arguments: 'valid_objf' and 'global_batch_idx_train'
```

(and also fix run.sh to call it ctc_train.py not train.py, same for decode).

**Comment by danpovey** [comment]
.. and verify ctc_decode.py  still works.
would be good task for someone outside core team.

**Comment by csukuangfj** [comment]
The following commit changed the interface for `load_checkpoint` and `save_checkpoint`.
https://github.com/k2-fsa/snowfall/pull/74

**Comment by csukuangfj** [comment]
Will fix it after setting up the k2-fsa.org server.

**Comment by csukuangfj** [comment]
Closing via https://github.com/k2-fsa/snowfall/pull/94
