### ISSUE TITLE
TypeError: linear_fsa() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by wangkaisine** [k2-fsa/snowfall#90]
egs/librispeech/asr/simple_v1/run.sh

python3 ./mmi_mbr_train.py

2021-02-04 22:15:14,543 INFO [mmi_mbr_train.py:552] epoch 0, learning rate 0.001
Traceback (most recent call last):
  File "./mmi_mbr_train.py", line 617, in <module>
    main()
  File "./mmi_mbr_train.py", line 564, in main
    global_batch_idx_train=global_batch_idx_train,
  File "./mmi_mbr_train.py", line 280, in train_one_epoch
    optimizer=optimizer)
  File "./mmi_mbr_train.py", line 114, in get_loss
    num_graph, den_graph, decoding_graph = graph_compiler.compile(texts, P)
  File "/home/w00423660/anaconda3/lib/python3.6/site-packages/snowfall-0.1-py3.6.egg/snowfall/training/mmi_mbr_graph.py", line 142, in compile
  File "/home/w00423660/anaconda3/lib/python3.6/site-packages/snowfall-0.1-py3.6.egg/snowfall/training/mmi_mbr_graph.py", line 187, in build_num_graphs
TypeError: linear_fsa() takes 1 positional argument but 2 were given

**Comment by csukuangfj** [comment]
Please use the latest k2.
```
pip install --pre k2
```

or install k2 from source.

**Comment by csukuangfj** [comment]
`pip install -r requirements.txt` does not install the latest k2.

**Comment by csukuangfj** [comment]
The following link may be helpful:

https://k2.readthedocs.io/en/latest/installation.html
